language: generic
sudo: required
services:
  - docker

before_install:
  # How to get <image-id>, use Github tag
  - docker build -t newenay/react-test -f ./client/Dockerfile.dev ./client

script:
  # Flag assures test suite will exit on completion
  # - docker run newenay/react-test npm test -- --coverage
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t newenay/multi-client ./client
  - docker build -t newenay/multi-nginx ./nginx
  - docker build -t newenay/multi-server ./server
  - docker build -t newenay/multi-worker ./worker