sudo: required
language: generic
services:
  - docker

before_install:
  # How to get <image-id>, use Github tag
  - docker build -t newenay/react-test -f ./client/Dockerfile.dev ./client

script:
  # Flag assures test suite will exit on completion
  # - docker run newenay/react-test npm test -- --coverage
  - docker run -e CI=true newenay/react-test npm test

after_success:
  - docker build -t newenay/multi-client ./client
  - docker build -t newenay/multi-nginx ./nginx
  - docker build -t newenay/multi-server ./server
  - docker build -t newenay/multi-worker ./worker
  
  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push newenay/multi-client
  - docker push newenay/multi-nginx
  - docker push newenay/multi-server
  - docker push newenay/multi-worker

deploy:
  # Travis CI knows what to do with this
  provider: elasticbeanstalk
  # found in url: http://multidocker-env.eba-g8phw9b5.us-east-1.elasticbeanstalk.com/

  region: 'us-east-1'
  # See pic on 07_readme.md for guidance
  app: 'multi-docker'
  env: 'Multidocker-env'
  # Search AWS searchbar for 'S3 bucket', then click 'buckets'
  bucket_name: 'elasticbeanstalk-us-east-1-123793844064'
  # folder may not yet exist in bucket, but name same as appName
  bucket_path: 'multi-docker'
  # only deploy master branches, not feature branches

  # environmental vars created in AWS (IAM), and imported in Travis
  access_key_id: $AWS_ACCESS_KEY
  # This one may need to be wrapped in double-quotes
  secret_access_key: $AWS_SECRET_KEY

  on:
    branch: master