version: '3'
services:

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: 'redis:latest'
  
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  api:
    build:
      dockerfile: Dockerfile.dev
      # Find all needed files in the following context
      context: ./server
    
    volumes:
      # Ignore this Folder
      - /app/node_modules
      # Everything in the server dir, should be shared 
      # with the app folder (except node_modules)
      - ./server:/app

    environment:
    # As defined above
    - REDIS_HOST=redis
    # Check documentation on dockerHub for default port
    - REDIS_PORT=6379
    # ?
    - PGUSER=postgres
    # As defined above
    - PGHOST=postgres
    # We will connect to default DB called..
    - PGDATABASE=postgres
    # Not documented on dockerHub?
    - PGPASSWORD=postgres_password
    # Check documentation on dockerHub for default port
    - PGPORT=5432
 
  
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0


  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379